// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oracle/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34238c8dfdfcd7ec, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34238c8dfdfcd7ec, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryCoinRatesRequest struct {
	RequestId int64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryCoinRatesRequest) Reset()         { *m = QueryCoinRatesRequest{} }
func (m *QueryCoinRatesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCoinRatesRequest) ProtoMessage()    {}
func (*QueryCoinRatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34238c8dfdfcd7ec, []int{2}
}
func (m *QueryCoinRatesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCoinRatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCoinRatesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCoinRatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCoinRatesRequest.Merge(m, src)
}
func (m *QueryCoinRatesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCoinRatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCoinRatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCoinRatesRequest proto.InternalMessageInfo

func (m *QueryCoinRatesRequest) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

type QueryCoinRatesResponse struct {
	Result *CoinRatesResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *QueryCoinRatesResponse) Reset()         { *m = QueryCoinRatesResponse{} }
func (m *QueryCoinRatesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCoinRatesResponse) ProtoMessage()    {}
func (*QueryCoinRatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34238c8dfdfcd7ec, []int{3}
}
func (m *QueryCoinRatesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCoinRatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCoinRatesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCoinRatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCoinRatesResponse.Merge(m, src)
}
func (m *QueryCoinRatesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCoinRatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCoinRatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCoinRatesResponse proto.InternalMessageInfo

func (m *QueryCoinRatesResponse) GetResult() *CoinRatesResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryLastCoinRatesIdRequest struct {
}

func (m *QueryLastCoinRatesIdRequest) Reset()         { *m = QueryLastCoinRatesIdRequest{} }
func (m *QueryLastCoinRatesIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLastCoinRatesIdRequest) ProtoMessage()    {}
func (*QueryLastCoinRatesIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34238c8dfdfcd7ec, []int{4}
}
func (m *QueryLastCoinRatesIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLastCoinRatesIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLastCoinRatesIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLastCoinRatesIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLastCoinRatesIdRequest.Merge(m, src)
}
func (m *QueryLastCoinRatesIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLastCoinRatesIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLastCoinRatesIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLastCoinRatesIdRequest proto.InternalMessageInfo

type QueryLastCoinRatesIdResponse struct {
	RequestId int64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryLastCoinRatesIdResponse) Reset()         { *m = QueryLastCoinRatesIdResponse{} }
func (m *QueryLastCoinRatesIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLastCoinRatesIdResponse) ProtoMessage()    {}
func (*QueryLastCoinRatesIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34238c8dfdfcd7ec, []int{5}
}
func (m *QueryLastCoinRatesIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLastCoinRatesIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLastCoinRatesIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLastCoinRatesIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLastCoinRatesIdResponse.Merge(m, src)
}
func (m *QueryLastCoinRatesIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLastCoinRatesIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLastCoinRatesIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLastCoinRatesIdResponse proto.InternalMessageInfo

func (m *QueryLastCoinRatesIdResponse) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

// this line is used by starport scaffolding # 3
type QueryGetCoinSymbolRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCoinSymbolRequest) Reset()         { *m = QueryGetCoinSymbolRequest{} }
func (m *QueryGetCoinSymbolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCoinSymbolRequest) ProtoMessage()    {}
func (*QueryGetCoinSymbolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34238c8dfdfcd7ec, []int{6}
}
func (m *QueryGetCoinSymbolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCoinSymbolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCoinSymbolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCoinSymbolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCoinSymbolRequest.Merge(m, src)
}
func (m *QueryGetCoinSymbolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCoinSymbolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCoinSymbolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCoinSymbolRequest proto.InternalMessageInfo

func (m *QueryGetCoinSymbolRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetCoinSymbolResponse struct {
	CoinSymbol CoinSymbol `protobuf:"bytes,1,opt,name=CoinSymbol,proto3" json:"CoinSymbol"`
}

func (m *QueryGetCoinSymbolResponse) Reset()         { *m = QueryGetCoinSymbolResponse{} }
func (m *QueryGetCoinSymbolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCoinSymbolResponse) ProtoMessage()    {}
func (*QueryGetCoinSymbolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34238c8dfdfcd7ec, []int{7}
}
func (m *QueryGetCoinSymbolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCoinSymbolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCoinSymbolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCoinSymbolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCoinSymbolResponse.Merge(m, src)
}
func (m *QueryGetCoinSymbolResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCoinSymbolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCoinSymbolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCoinSymbolResponse proto.InternalMessageInfo

func (m *QueryGetCoinSymbolResponse) GetCoinSymbol() CoinSymbol {
	if m != nil {
		return m.CoinSymbol
	}
	return CoinSymbol{}
}

type QueryAllCoinSymbolRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCoinSymbolRequest) Reset()         { *m = QueryAllCoinSymbolRequest{} }
func (m *QueryAllCoinSymbolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCoinSymbolRequest) ProtoMessage()    {}
func (*QueryAllCoinSymbolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34238c8dfdfcd7ec, []int{8}
}
func (m *QueryAllCoinSymbolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCoinSymbolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCoinSymbolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCoinSymbolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCoinSymbolRequest.Merge(m, src)
}
func (m *QueryAllCoinSymbolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCoinSymbolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCoinSymbolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCoinSymbolRequest proto.InternalMessageInfo

func (m *QueryAllCoinSymbolRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCoinSymbolResponse struct {
	CoinSymbol []CoinSymbol        `protobuf:"bytes,1,rep,name=CoinSymbol,proto3" json:"CoinSymbol"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCoinSymbolResponse) Reset()         { *m = QueryAllCoinSymbolResponse{} }
func (m *QueryAllCoinSymbolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCoinSymbolResponse) ProtoMessage()    {}
func (*QueryAllCoinSymbolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34238c8dfdfcd7ec, []int{9}
}
func (m *QueryAllCoinSymbolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCoinSymbolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCoinSymbolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCoinSymbolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCoinSymbolResponse.Merge(m, src)
}
func (m *QueryAllCoinSymbolResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCoinSymbolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCoinSymbolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCoinSymbolResponse proto.InternalMessageInfo

func (m *QueryAllCoinSymbolResponse) GetCoinSymbol() []CoinSymbol {
	if m != nil {
		return m.CoinSymbol
	}
	return nil
}

func (m *QueryAllCoinSymbolResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "spidex.oracle.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "spidex.oracle.v1.QueryParamsResponse")
	proto.RegisterType((*QueryCoinRatesRequest)(nil), "spidex.oracle.v1.QueryCoinRatesRequest")
	proto.RegisterType((*QueryCoinRatesResponse)(nil), "spidex.oracle.v1.QueryCoinRatesResponse")
	proto.RegisterType((*QueryLastCoinRatesIdRequest)(nil), "spidex.oracle.v1.QueryLastCoinRatesIdRequest")
	proto.RegisterType((*QueryLastCoinRatesIdResponse)(nil), "spidex.oracle.v1.QueryLastCoinRatesIdResponse")
	proto.RegisterType((*QueryGetCoinSymbolRequest)(nil), "spidex.oracle.v1.QueryGetCoinSymbolRequest")
	proto.RegisterType((*QueryGetCoinSymbolResponse)(nil), "spidex.oracle.v1.QueryGetCoinSymbolResponse")
	proto.RegisterType((*QueryAllCoinSymbolRequest)(nil), "spidex.oracle.v1.QueryAllCoinSymbolRequest")
	proto.RegisterType((*QueryAllCoinSymbolResponse)(nil), "spidex.oracle.v1.QueryAllCoinSymbolResponse")
}

func init() { proto.RegisterFile("oracle/v1/query.proto", fileDescriptor_34238c8dfdfcd7ec) }

var fileDescriptor_34238c8dfdfcd7ec = []byte{
	// 664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xcf, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x37, 0xdb, 0x76, 0xc1, 0x11, 0x7f, 0x30, 0xb6, 0xb5, 0xa6, 0x6d, 0xb4, 0xb1, 0xda,
	0x5f, 0x36, 0xc3, 0x56, 0x2c, 0x78, 0xf0, 0xd0, 0x56, 0x2c, 0x05, 0x85, 0x9a, 0xde, 0xbc, 0xac,
	0xb3, 0xc9, 0x10, 0x03, 0xd9, 0x4c, 0x9a, 0x99, 0x2c, 0x2e, 0xc5, 0x8b, 0x7f, 0x81, 0x20, 0x88,
	0xe0, 0x5f, 0xe0, 0x7f, 0xd2, 0x63, 0xc1, 0x8b, 0x27, 0x91, 0x5d, 0xaf, 0xfe, 0x0f, 0xb2, 0x33,
	0x93, 0x26, 0xcd, 0x26, 0x6c, 0xbd, 0x0d, 0xf3, 0xbe, 0xef, 0xbd, 0xcf, 0x9b, 0xfd, 0xbe, 0x2c,
	0x98, 0xa1, 0x31, 0x76, 0x02, 0x82, 0xba, 0x4d, 0x74, 0x9c, 0x90, 0xb8, 0x67, 0x45, 0x31, 0xe5,
	0x14, 0xde, 0x64, 0x91, 0xef, 0x92, 0xf7, 0x96, 0x8c, 0x5a, 0xdd, 0xa6, 0x3e, 0xed, 0x51, 0x8f,
	0x8a, 0x20, 0x1a, 0x9e, 0xa4, 0x4e, 0x5f, 0xf0, 0x28, 0xf5, 0x02, 0x82, 0x70, 0xe4, 0x23, 0x1c,
	0x86, 0x94, 0x63, 0xee, 0xd3, 0x90, 0xa9, 0xe8, 0xba, 0x43, 0x59, 0x87, 0x32, 0xd4, 0xc6, 0x8c,
	0xc8, 0xf2, 0xa8, 0xdb, 0x6c, 0x13, 0x8e, 0x9b, 0x28, 0xc2, 0x9e, 0x1f, 0x0a, 0xb1, 0xd2, 0xce,
	0x66, 0x20, 0x11, 0x8e, 0x71, 0x27, 0xad, 0xa1, 0x67, 0xf7, 0x0e, 0xf5, 0xc3, 0x56, 0x8c, 0x39,
	0x49, 0x63, 0xf3, 0x85, 0x18, 0xeb, 0x75, 0xda, 0x34, 0x90, 0x41, 0x73, 0x1a, 0xc0, 0xd7, 0xc3,
	0x96, 0x87, 0xa2, 0x9a, 0x4d, 0x8e, 0x13, 0xc2, 0xb8, 0xf9, 0x0a, 0xdc, 0xba, 0x70, 0xcb, 0x22,
	0x1a, 0x32, 0x02, 0xb7, 0x41, 0x43, 0x76, 0x9d, 0xd3, 0xee, 0x69, 0xab, 0x57, 0xb7, 0xe6, 0xac,
	0xe2, 0x03, 0x58, 0x32, 0x63, 0x77, 0xf2, 0xf4, 0xd7, 0xdd, 0x9a, 0xad, 0xd4, 0xe6, 0x36, 0x98,
	0x11, 0xe5, 0xf6, 0xa8, 0x1f, 0xda, 0x43, 0x32, 0xd5, 0x07, 0x2e, 0x02, 0x10, 0xcb, 0x63, 0xcb,
	0x77, 0x45, 0xd1, 0x09, 0xfb, 0x8a, 0xba, 0x39, 0x70, 0xcd, 0x23, 0x30, 0x5b, 0xcc, 0x53, 0x24,
	0x4f, 0x41, 0x23, 0x26, 0x2c, 0x09, 0xb8, 0x22, 0x59, 0x1a, 0x25, 0xc9, 0x27, 0x25, 0x01, 0xb7,
	0x55, 0x82, 0xb9, 0x08, 0xe6, 0x45, 0xd1, 0x97, 0x98, 0xf1, 0x73, 0xcd, 0x81, 0x9b, 0x8e, 0xfe,
	0x0c, 0x2c, 0x94, 0x87, 0x55, 0xe7, 0x31, 0xc8, 0x1b, 0xe0, 0x8e, 0x48, 0xdf, 0x27, 0x22, 0xfb,
	0x48, 0xbc, 0x75, 0x3a, 0xee, 0x75, 0x50, 0x57, 0x39, 0x93, 0x76, 0xdd, 0x77, 0xcd, 0xb7, 0x40,
	0x2f, 0x13, 0xab, 0x4e, 0xbb, 0x00, 0x64, 0xb7, 0x6a, 0xce, 0x85, 0xf2, 0x39, 0xa5, 0x46, 0xbd,
	0x7a, 0x2e, 0xcb, 0x74, 0x14, 0xce, 0x4e, 0x10, 0x8c, 0xe2, 0xbc, 0x00, 0x20, 0x33, 0x98, 0x6a,
	0xf0, 0xd0, 0x92, 0x6e, 0xb4, 0x86, 0x6e, 0xb4, 0xa4, 0xd9, 0x95, 0x1b, 0xad, 0x43, 0xec, 0x11,
	0x95, 0x6b, 0xe7, 0x32, 0xcd, 0xef, 0x9a, 0x9a, 0xa3, 0xd0, 0xa5, 0x62, 0x8e, 0x89, 0xff, 0x9f,
	0x03, 0xee, 0x5f, 0x40, 0xad, 0x0b, 0xd4, 0x95, 0xb1, 0xa8, 0x12, 0x20, 0xcf, 0xba, 0xf5, 0x77,
	0x0a, 0x4c, 0x09, 0x56, 0xc8, 0x41, 0x43, 0x9a, 0x15, 0x2e, 0x8f, 0xc2, 0x8c, 0xee, 0x84, 0xfe,
	0x60, 0x8c, 0x4a, 0x36, 0x33, 0x17, 0x3f, 0xfe, 0xf8, 0xf3, 0xb9, 0x7e, 0x1b, 0xce, 0x20, 0x29,
	0x47, 0x6a, 0xfb, 0xe4, 0x2a, 0xc0, 0x6f, 0x1a, 0xb8, 0x51, 0x70, 0x26, 0x5c, 0xa9, 0xa8, 0x5c,
	0x5c, 0x17, 0x7d, 0x75, 0xbc, 0x50, 0x51, 0x3c, 0x11, 0x14, 0x08, 0x6e, 0x16, 0x28, 0xb2, 0x8f,
	0x43, 0x4b, 0xae, 0x03, 0x3a, 0xc9, 0xdc, 0xfc, 0x41, 0xd0, 0x15, 0x8c, 0x0f, 0x37, 0x2b, 0x9a,
	0x96, 0xef, 0x8f, 0x6e, 0x5d, 0x56, 0xae, 0x48, 0xd7, 0x04, 0xe9, 0x7d, 0xb8, 0x54, 0x20, 0x0d,
	0x30, 0xe3, 0xad, 0x1c, 0xae, 0xef, 0xc2, 0xaf, 0x5a, 0xde, 0x49, 0x70, 0xa3, 0xa2, 0x53, 0xd9,
	0xea, 0xe9, 0x8f, 0x2e, 0x27, 0x56, 0x50, 0x48, 0x40, 0xad, 0xc1, 0x15, 0xb4, 0x47, 0x03, 0xca,
	0x18, 0x49, 0x3a, 0x3b, 0xc8, 0x49, 0x8f, 0x38, 0xff, 0x1d, 0x45, 0x27, 0xc3, 0x87, 0xfb, 0xa2,
	0x81, 0x6b, 0x59, 0x9d, 0x9d, 0xa0, 0x9a, 0xae, 0x6c, 0x13, 0x2b, 0xe9, 0x4a, 0x17, 0xca, 0x5c,
	0x17, 0x74, 0xcb, 0xd0, 0x1c, 0x4f, 0xb7, 0xfb, 0xfc, 0xb4, 0x6f, 0x68, 0x67, 0x7d, 0x43, 0xfb,
	0xdd, 0x37, 0xb4, 0x4f, 0x03, 0xa3, 0x76, 0x36, 0x30, 0x6a, 0x3f, 0x07, 0x46, 0xed, 0xcd, 0xba,
	0xe7, 0xf3, 0x77, 0x49, 0xdb, 0x72, 0x68, 0x47, 0x3d, 0x3d, 0x8e, 0xa2, 0xf4, 0x47, 0x38, 0xff,
	0x19, 0x78, 0x2f, 0x22, 0xac, 0xdd, 0x10, 0x7f, 0x16, 0x8f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x9a, 0xf0, 0x07, 0x02, 0x08, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// CoinRatesResult defines a rpc handler method for MsgCoinRatesData.
	CoinRatesResult(ctx context.Context, in *QueryCoinRatesRequest, opts ...grpc.CallOption) (*QueryCoinRatesResponse, error)
	// LastCoinRatesId query the last CoinRates result id
	LastCoinRatesId(ctx context.Context, in *QueryLastCoinRatesIdRequest, opts ...grpc.CallOption) (*QueryLastCoinRatesIdResponse, error)
	// Queries a CoinSymbol by id.
	CoinSymbol(ctx context.Context, in *QueryGetCoinSymbolRequest, opts ...grpc.CallOption) (*QueryGetCoinSymbolResponse, error)
	// Queries a list of CoinSymbol items.
	CoinSymbolAll(ctx context.Context, in *QueryAllCoinSymbolRequest, opts ...grpc.CallOption) (*QueryAllCoinSymbolResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/spidex.oracle.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CoinRatesResult(ctx context.Context, in *QueryCoinRatesRequest, opts ...grpc.CallOption) (*QueryCoinRatesResponse, error) {
	out := new(QueryCoinRatesResponse)
	err := c.cc.Invoke(ctx, "/spidex.oracle.v1.Query/CoinRatesResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastCoinRatesId(ctx context.Context, in *QueryLastCoinRatesIdRequest, opts ...grpc.CallOption) (*QueryLastCoinRatesIdResponse, error) {
	out := new(QueryLastCoinRatesIdResponse)
	err := c.cc.Invoke(ctx, "/spidex.oracle.v1.Query/LastCoinRatesId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CoinSymbol(ctx context.Context, in *QueryGetCoinSymbolRequest, opts ...grpc.CallOption) (*QueryGetCoinSymbolResponse, error) {
	out := new(QueryGetCoinSymbolResponse)
	err := c.cc.Invoke(ctx, "/spidex.oracle.v1.Query/CoinSymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CoinSymbolAll(ctx context.Context, in *QueryAllCoinSymbolRequest, opts ...grpc.CallOption) (*QueryAllCoinSymbolResponse, error) {
	out := new(QueryAllCoinSymbolResponse)
	err := c.cc.Invoke(ctx, "/spidex.oracle.v1.Query/CoinSymbolAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// CoinRatesResult defines a rpc handler method for MsgCoinRatesData.
	CoinRatesResult(context.Context, *QueryCoinRatesRequest) (*QueryCoinRatesResponse, error)
	// LastCoinRatesId query the last CoinRates result id
	LastCoinRatesId(context.Context, *QueryLastCoinRatesIdRequest) (*QueryLastCoinRatesIdResponse, error)
	// Queries a CoinSymbol by id.
	CoinSymbol(context.Context, *QueryGetCoinSymbolRequest) (*QueryGetCoinSymbolResponse, error)
	// Queries a list of CoinSymbol items.
	CoinSymbolAll(context.Context, *QueryAllCoinSymbolRequest) (*QueryAllCoinSymbolResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) CoinRatesResult(ctx context.Context, req *QueryCoinRatesRequest) (*QueryCoinRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoinRatesResult not implemented")
}
func (*UnimplementedQueryServer) LastCoinRatesId(ctx context.Context, req *QueryLastCoinRatesIdRequest) (*QueryLastCoinRatesIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastCoinRatesId not implemented")
}
func (*UnimplementedQueryServer) CoinSymbol(ctx context.Context, req *QueryGetCoinSymbolRequest) (*QueryGetCoinSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoinSymbol not implemented")
}
func (*UnimplementedQueryServer) CoinSymbolAll(ctx context.Context, req *QueryAllCoinSymbolRequest) (*QueryAllCoinSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoinSymbolAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidex.oracle.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CoinRatesResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCoinRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CoinRatesResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidex.oracle.v1.Query/CoinRatesResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CoinRatesResult(ctx, req.(*QueryCoinRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastCoinRatesId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLastCoinRatesIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastCoinRatesId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidex.oracle.v1.Query/LastCoinRatesId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastCoinRatesId(ctx, req.(*QueryLastCoinRatesIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CoinSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCoinSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CoinSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidex.oracle.v1.Query/CoinSymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CoinSymbol(ctx, req.(*QueryGetCoinSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CoinSymbolAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCoinSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CoinSymbolAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidex.oracle.v1.Query/CoinSymbolAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CoinSymbolAll(ctx, req.(*QueryAllCoinSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spidex.oracle.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "CoinRatesResult",
			Handler:    _Query_CoinRatesResult_Handler,
		},
		{
			MethodName: "LastCoinRatesId",
			Handler:    _Query_LastCoinRatesId_Handler,
		},
		{
			MethodName: "CoinSymbol",
			Handler:    _Query_CoinSymbol_Handler,
		},
		{
			MethodName: "CoinSymbolAll",
			Handler:    _Query_CoinSymbolAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCoinRatesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCoinRatesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCoinRatesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCoinRatesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCoinRatesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCoinRatesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLastCoinRatesIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLastCoinRatesIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLastCoinRatesIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLastCoinRatesIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLastCoinRatesIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLastCoinRatesIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCoinSymbolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCoinSymbolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCoinSymbolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCoinSymbolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCoinSymbolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCoinSymbolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CoinSymbol.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCoinSymbolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCoinSymbolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCoinSymbolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCoinSymbolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCoinSymbolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCoinSymbolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CoinSymbol) > 0 {
		for iNdEx := len(m.CoinSymbol) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CoinSymbol[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCoinRatesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func (m *QueryCoinRatesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLastCoinRatesIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLastCoinRatesIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func (m *QueryGetCoinSymbolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetCoinSymbolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CoinSymbol.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCoinSymbolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCoinSymbolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CoinSymbol) > 0 {
		for _, e := range m.CoinSymbol {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCoinRatesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCoinRatesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCoinRatesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCoinRatesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCoinRatesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCoinRatesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &CoinRatesResult{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLastCoinRatesIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLastCoinRatesIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLastCoinRatesIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLastCoinRatesIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLastCoinRatesIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLastCoinRatesIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCoinSymbolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCoinSymbolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCoinSymbolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCoinSymbolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCoinSymbolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCoinSymbolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinSymbol", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CoinSymbol.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCoinSymbolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCoinSymbolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCoinSymbolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCoinSymbolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCoinSymbolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCoinSymbolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinSymbol", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CoinSymbol = append(m.CoinSymbol, CoinSymbol{})
			if err := m.CoinSymbol[len(m.CoinSymbol)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
